version: "3.9"

services:
    image_uploader:
        build: .
        environment:
            - IMAGE_STORE_DIR=/opt/image_bucket
        ports:
            - 19000:9000
        volumes:
            - ${IMAGE_STORE_DIR:-/opt/image_bucket}:${IMAGE_STORE_DIR:-/opt/image_bucket}
        #restart: always

